
## found a bug? sxkadamn (ds) :
time: 10 #время в секундах скольок будет идти проверка!

menuName: "&6Против ботиков, ха-ха-ха!"

correctName: "&aЯ не бот&7(&6нажми&7)"
correctLore: "&a&nНажми сюда, если ты не бот!"

incorrectName: "&aЯ бот&7(&6нажми&7)"
incorrectLore: "&c&nНажми сюда, если ты бот!"


messages:
  close: "&cВы не прошли проверку! Так как закрыли менюшку!"
  failed: "&cВы не прошли проверку!"
  success: "&aВы прошли проверку! Удачной игры!"
  already: "&aВы уже прошли проверку!"
  time_left: "&6Вы не успели пройти проверку на бота"